### ISSUE TITLE
提醒：当前nodejs(v10.16.0, v12.4.0) http2存在内存泄漏问题，关联模块：GRPC

### ISSUE THREAD

**Issue by RabbitSion** [sofastack/sofa-rpc-node#50]
GRPC模块在使用时存在内存泄漏问题，问题发现为nodejs的http2模块问题。
在此提出issue标记一下该问题，提醒被内存泄漏困扰的开发。issue地址：
[https://github.com/nodejs/node/issues/28088](https://github.com/nodejs/node/issues/28088)

**Comment by gxcsoccer** [comment]
等 node 下个版本修复？

**Comment by RabbitSion** [comment]
嗯，只能关注node下个版本了。当前只能提醒使用grpc-server模块的开发：上生产环境要慎重

**Comment by gxcsoccer** [comment]
@RabbitSion 其实现在也没正式对外说

**Comment by RabbitSion** [comment]
node 12.9.0 已确认修复了该内存泄漏的问题

**Comment by fengmk2** [comment]
可以正式推广使用了？

**Comment by RabbitSion** [comment]
我这块的一个月的线上使用情况正常。正式推广使用的标准是否达到，我这边还没有进行对应的压测和性能分析。业务上：node微服务下的rpc的断路器也不是特别完善，个人拙见还是是局部试点。
