### ISSUE TITLE
是否提供sofa-rpc-node.d.ts？

### ISSUE THREAD

**Issue by cevio** [sofastack/sofa-rpc-node#54]
ts写的node服务根本无法调用，是否官方可以支持？

**Comment by gxcsoccer** [comment]
你是说调用服务，还是暴露服务？

这个库是底层库，ts 支持我们是在 egg 层面上支持的

**Comment by cevio** [comment]
@gxcsoccer 

> 你是说调用服务，还是暴露服务？
> 
> 这个库是底层库，ts 支持我们是在 egg 层面上支持的

在不使用egg的时候。单独使用sofa。

还有在使用过程中还发现一个问题 `uniqueId` 根本不起作用。我的解决方案是在内网fork一份，然后自己修改uniqueId。

我不明白的是，为什么uniqueId你们不考虑，在阿里内部这个字段没有作用吗？

**Comment by gxcsoccer** [comment]
uniqueId 内部是有作用的，反而是开源的实现没作用

**Comment by gxcsoccer** [comment]
@cevio 我们还是建议走 egg，很多功能都是走插件形式来封装的。这个库是底层的

**Comment by cevio** [comment]
@gxcsoccer 我基本已经搞定了，我自己写了.d.ts。还是谢谢您
