### ISSUE TITLE
sofa node作为客户端，调用使用hessian4的版本的服务端，出现异常

### ISSUE THREAD

**Issue by xiaoni157** [sofastack/sofa-rpc-node#57]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

服务端使用默认hessian3序列化版本，用node客户端去调用服务端，服务端可以正常接收请求，并返回，
但是当服务端hessian版本换成4的话，使用原来的node代码去调用的时候，出现异常，服务端未收到请求，我猜是序列化的问题，以下是错误日志：
![image](https://user-images.githubusercontent.com/24448049/60874673-f6103080-a26a-11e9-81b9-887b8574e313.png)，寻求专业解答。

**Comment by gxcsoccer** [comment]
目前 node 客户端不支持 hessian4

**Comment by trexguo** [comment]
计划什么时候支持呢？

**Comment by gxcsoccer** [comment]
5月底吧，抽空搞下

**Comment by gxcsoccer** [comment]
https://github.com/sofastack/sofa-bolt-node/pull/11

这个合并以后支持

```js
const protocol = require('sofa-bolt-node');
protocol.setHessianVersion('4.0');

const { RpcClient } = require('sofa-rpc-node').client;

const client = new RpcClient({
  logger: console,
  protocol,
});
```

**Comment by gxcsoccer** [comment]
安装 egg-sofa-rpc@3.0.0

```js
// config.default.js

exports.rpc = {
  hessianVersion: '4.0',
};
```
