### ISSUE TITLE
sofa-rpc-node 是否支持 sofatracer 透传 功能

### ISSUE THREAD

**Issue by oka96** [sofastack/sofa-rpc-node#99]
java 版本 sofarpc 可以通过 RpcInvokeContext 把数据给透传。想问node 版本是否支持？

**Comment by JervyShi** [comment]
可以看下这个 test case 中的示例 https://github.com/sofastack/sofa-rpc-node/blob/3e04f15d568470375117edb8bdde62278a049f6c/test/server/connection.test.js#L100-L117
